on:
    workflow_dispatch:
    push:
        branches:
            -main
name: Update Readme
jobs:
    updateReadme:
        name: Update Readme
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@main
              with:
                fetch-depth: 1
            - name: Generate Readme.md
              run: .\scripts\Generate-Readme.ps1
              shell: pwsh
            - name: Push updates
              run: |
                git config user.name "Github Actions"
                git config user.email "<>"
                git add Readme.md
                git commit -m "[Bot] Update readme"
                git push origin main

